### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by manson-2020** [hemengke1997/vscode-image-manager#12]
可以在侧边栏加个入口吗

**Comment by hemengke1997** [comment]
侧边栏不能直接打开edtior中的界面，必须先在侧边栏创建视图
你有什么实现想法吗

**Comment by hemengke1997** [comment]
<img width="366" alt="image" src="https://github.com/hemengke1997/vscode-image-manager/assets/49073282/76c27775-0ee3-4a74-a8ac-b3b9c324f961">

就是这样的，感觉反而更麻烦了。快捷键/右键菜单，我觉得挺方便的。你是觉得哪里不方便使用吗

**Comment by manson-2020** [comment]
我以为它可以像资源管理那样一个列表展示出来并且可操作，这样子在写代码的同时就能查看和操作图片，而不用再打开一个tab

**Comment by hemengke1997** [comment]
PR welcome
