### ISSUE TITLE
新增转换类型 —— ico

### ISSUE THREAD

**Issue by Vanisper** [hemengke1997/vscode-image-manager#14]
如题，希望新增图像转换的类型—— ico 格式。
因为在web开发中，favicon 一般都是ico格式的，虽然说其他格式也支持，但是也希望能有此项类型转换。

**Comment by hemengke1997** [comment]
这种场景一般是把哪些图片类型转ico呢？
是否有必要ico转其他类型呢？

**Comment by Vanisper** [comment]
> 这种场景一般是把哪些图片类型转ico呢？ 是否有必要ico转其他类型呢？

一般图像都应该可以转 `ico图像`，当然理想中ico也应该是可以转回去，但是一般来说 ico图像 像素都比较差（但是这貌似不是程序需要考虑的事情，是使用者决策的问题）。

大佬可以看一下这个网站 [https://convertio.co/zh/image-converter/](https://convertio.co/zh/image-converter/)
他是可以实现所有图像文件的互转（当然不限于图像文件，像pdf转png，他会智能的将pdf各也转成png然后打包供下载，当然此功能不是本项目需要考虑的需求）

**Comment by Vanisper** [comment]
但是图像的转换应该有一个路径，
就比如说svg转ico，可能不能一步到位，需要先svg转png再由png转svg，

> 以上的这个转换路径是个人猜测，仅供参考，
> 但是我觉得这种模式的应该还有不少，为了开发的便利，就是可能需要考虑的是在程序开发之时，将各个图像格式之间的转换弄成 `配置式` 的，然后，其中一个配置项为”转换路径“，设定好配置然后，通过执行此配置能够按照配置好的 **转换路径** ，自驱地执行转换过程，
> 如此的话，需要做的就是封装好各个节点的转换方法，以及各个转换之间的 **io协同**。
> 思路仅供参考哈

**Comment by hemengke1997** [comment]
Supported in `v0.16.0`

转化格式中新增了对ico文件的支持
新增了 `image-manager.conversion.icoSize`，可自行配置ico图标大小，默认32x32
