### ISSUE TITLE
mac 还是用户不了

### ISSUE THREAD

**Issue by mxp131011** [hemengke1997/vscode-image-manager#15]
mac 还是用户不了 手动下载
 https://registry.npmmirror.com/-/binary/sharp-libvips/v8.14.5/libvips-8.14.5-darwin-arm64v8.tar.br
 https://registry.npmmirror.com/-/binary/sharp/v0.32.6/sharp-v0.32.6-napi-v7-darwin-arm64.tar.gz
 并放到
 /Users/maxiaoping/.vscode/extensions/minko.image-manager-0.15.1/
 下无效，不知道位置是否正确还是需要解压了在放

**Comment by hemengke1997** [comment]
重启vscode后，打开插件的output channel，截图我看看

**Comment by mxp131011** [comment]
![image](https://github.com/hemengke1997/vscode-image-manager/assets/31055355/e39fded1-2537-4a28-ac47-8187ed10f999)

**Comment by mxp131011** [comment]
> 重启vscode后，打开插件的output channel，截图我看看

如上

**Comment by hemengke1997** [comment]
我现在电脑不在身边，明天我这边修复。
但是你也可以临时处理，就是把图上那个json文件里面写个空对象就行了

**Comment by mxp131011** [comment]
好的	谢谢

**Comment by hemengke1997** [comment]
fixed in `0.15.2`
