### ISSUE TITLE
加载核心脚本失败，请重试

### ISSUE THREAD

**Issue by manson-2020** [hemengke1997/vscode-image-manager#20]
打开就报错，重启了还是不对

**Comment by hemengke1997** [comment]
目前使用的什么版本？

**Comment by manson-2020** [comment]
最新的

**Comment by manson-2020** [comment]
![image](https://github.com/hemengke1997/vscode-image-manager/assets/43368308/c6878ae0-a4d2-4308-b46c-d48ca9224e01)

**Comment by hemengke1997** [comment]
升级到 `1.2.0`，如果还是弹出报错的提示，点击 立即重启 ，然后再尝试启动插件

**Comment by manson-2020** [comment]
![image](https://github.com/hemengke1997/vscode-image-manager/assets/43368308/4468f482-a896-426f-9d91-3ab3fd7870de)

**Comment by hemengke1997** [comment]
加我vx 23536175

**Comment by hemengke1997** [comment]
fixed in `1.2.1`

**Comment by hemengke1997** [comment]
> [Image Manager] 依赖安装流程结束 [Image Manager] ✅ Image Manager 初始化完成 [Image Manager] 根工作区: /Users/zhoudajun/Code/rbp-client/common_base/sound_lover/assets [Image Manager] libvips 开始自动安装依赖 [Image Manager] sharp binary 开始自动安装依赖: sharp-v1.1.0-napi-v7-darwin-arm64.tar.gz, sharp-v1.1.0-napi-v7-darwin-x64.tar.gz, sharp-v1.1.0-napi-v7-linux-x64.tar.gz, sharp-v1.1.0-napi-v7-linuxmusl-x64.tar.gz, sharp-v1.1.0-napi-v7-win32-ia32.tar.gz, sharp-v1.1.0-napi-v7-win32-x64.tar.gz [Image Manager] 依赖安装流程结束 [Image Manager] ✅ Image Manager 初始化完成
> 
> 最新版本还是打不开, 只能老老实实用0.24

升级到 `1.2.2` 即可
