### ISSUE TITLE
需求：能不能添加一个批量操作的功能呀

### ISSUE THREAD

**Issue by YL-python** [hemengke1997/vscode-image-manager#21]
现在我用这个插件，最多的是压缩我本地的图片，因为我是本地写记笔，然后用git同步，写笔记的时候截图会存在一个固定的目录里面，现在的场景是，每次写完笔记，我需要压缩图片存到git，但是图片多了，就很麻烦，期望大佬能添加一个批量操作的功能

**Comment by hemengke1997** [comment]
右键目录可以批量操作

**Comment by hemengke1997** [comment]
cmd/shift + 左键也可以多选批量操作
