### ISSUE TITLE
command 'image-manager.open-image-manager' not found

### ISSUE THREAD

**Issue by Wind2009-Louse** [hemengke1997/vscode-image-manager#23]
系统：Windows
版本号：v2.3.3

使用Alt+Shift+J无法打开页面，命令打开报错：
![image](https://github.com/user-attachments/assets/30191e1d-c8d3-4ec5-8cab-a34bafc42fa3)

---

重新安装2.3.2可以正常使用，不知道是不是2.3.3出了什么问题

**Comment by hemengke1997** [comment]
谢谢反馈，已修复，请升级 2.3.4
